/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.ImageIcon;

/**
 *
 * @author shiva
 */
public class Calculator extends javax.swing.JFrame {

    double firstnum;
     double secondnum;
      double result;
       String operations;
       
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        setTitle("Calculator");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtDisplay = new javax.swing.JTextField();
        jBtnNeg = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jBtnCanAll = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnPos = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnMul = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnEquals = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnPiont = new javax.swing.JButton();
        jBtnMix = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 312, 47));

        jBtnNeg.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNeg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnNeg.setText("-");
        jBtnNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNegActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 70, 60));

        jBtnBack.setBackground(new java.awt.Color(255, 255, 255));
        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnBack.setText("<-");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 60));

        jBtnCanAll.setBackground(new java.awt.Color(255, 255, 255));
        jBtnCanAll.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnCanAll.setText("C");
        jBtnCanAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCanAllActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCanAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 150, 60));

        jBtnDiv.setBackground(new java.awt.Color(255, 255, 255));
        jBtnDiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 70, 61));

        jBtn7.setBackground(new java.awt.Color(255, 255, 255));
        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 60));

        jBtn8.setBackground(new java.awt.Color(255, 255, 255));
        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 60));

        jBtn9.setBackground(new java.awt.Color(255, 255, 255));
        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 70, 60));

        jBtnPos.setBackground(new java.awt.Color(255, 255, 255));
        jBtnPos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnPos.setText("+");
        jBtnPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 70, 60));

        jBtn4.setBackground(new java.awt.Color(255, 255, 255));
        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 60));

        jBtn5.setBackground(new java.awt.Color(255, 255, 255));
        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, 60));

        jBtn6.setBackground(new java.awt.Color(255, 255, 255));
        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 70, 60));

        jBtnMul.setBackground(new java.awt.Color(255, 255, 255));
        jBtnMul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnMul.setText("*");
        jBtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMulActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 70, 60));

        jBtn1.setBackground(new java.awt.Color(255, 255, 255));
        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 60));

        jBtn2.setBackground(new java.awt.Color(255, 255, 255));
        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, 60));

        jBtn3.setBackground(new java.awt.Color(255, 255, 255));
        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 70, 60));

        jBtnEquals.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEquals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnEquals.setText("=");
        jBtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 70, 60));

        jBtn0.setBackground(new java.awt.Color(255, 255, 255));
        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 60));

        jBtnPiont.setBackground(new java.awt.Color(255, 255, 255));
        jBtnPiont.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnPiont.setText(".");
        jBtnPiont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiontActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPiont, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 70, 60));

        jBtnMix.setBackground(new java.awt.Color(255, 255, 255));
        jBtnMix.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnMix.setText("+/-");
        jBtnMix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMixActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMix, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 70, 60));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USE A SIMPLE CALCULATOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn7.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn7.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn8.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn8.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn9.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn9.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn4.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn4.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn5.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn5.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn6.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn6.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn1.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn1.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn2.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn2.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn3.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn3.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        // TODO add your handling code here:
        String EnterNumber=jTxtDisplay.getText();
        if(EnterNumber==""){
            jTxtDisplay.setText(jBtn0.getText());
        }else{
            EnterNumber=jTxtDisplay.getText()+jBtn0.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnPiontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiontActionPerformed
        // TODO add your handling code here:
        if(! jTxtDisplay.getText().contains(".")){
            jTxtDisplay.setText(jTxtDisplay.getText()+jBtnPiont.getText());
                    
        }
    }//GEN-LAST:event_jBtnPiontActionPerformed

    private void jBtnCanAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCanAllActionPerformed
        // TODO add your handling code here:
        jTxtDisplay.setText("");
    }//GEN-LAST:event_jBtnCanAllActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        String backspace=null;
        if(jTxtDisplay.getText().length()>0){
            StringBuilder strB=new StringBuilder(jTxtDisplay.getText());
            strB.deleteCharAt(jTxtDisplay.getText().length()-1);
            backspace=strB.toString();
            jTxtDisplay.setText(backspace);
        }
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNegActionPerformed
        // TODO add your handling code here:
         firstnum=Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText("");
        operations="-";
    }//GEN-LAST:event_jBtnNegActionPerformed

    private void jBtnPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPosActionPerformed
        // TODO add your handling code here:
         firstnum=Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText("");
        operations="+";
    }//GEN-LAST:event_jBtnPosActionPerformed

    private void jBtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMulActionPerformed
        // TODO add your handling code here:
         firstnum=Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_jBtnMulActionPerformed

    private void jBtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualsActionPerformed
        
        String answer;
        
        secondnum=Double.parseDouble(jTxtDisplay.getText());
        
        if(operations == "+"){
            result=firstnum+secondnum;
            answer= String.format("%.2f", result);
            jTxtDisplay.setText(answer);
        }else if(operations == "-"){
            result=firstnum-secondnum;
            answer= String.format("%.2f", result);
            jTxtDisplay.setText(answer);
        }else if(operations == "/"){
            result=firstnum/secondnum;
            answer= String.format("%.2f", result);
            jTxtDisplay.setText(answer);
        }else if(operations == "*"){
            result=firstnum*secondnum;
            answer= String.format("%.2f", result);
            jTxtDisplay.setText(answer);
        }
        
        
        
    }//GEN-LAST:event_jBtnEqualsActionPerformed

    private void jBtnMixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMixActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        ops=ops * (-1);
          jTxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnMixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnCanAll;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnEquals;
    private javax.swing.JButton jBtnMix;
    private javax.swing.JButton jBtnMul;
    private javax.swing.JButton jBtnNeg;
    private javax.swing.JButton jBtnPiont;
    private javax.swing.JButton jBtnPos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtDisplay;
    // End of variables declaration//GEN-END:variables
}
